use_frameworks!

target 'Peloton-UIColors_Example' do
  pod 'Peloton-UIColors', :path => '../'

  target 'Peloton-UIColors_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase', '~> 2.1'
    pod 'Quick', '~> 0.10'
    pod 'Nimble', '~> 5.0'
    pod 'Nimble-Snapshots', '~> 4.2'
  end
end
