# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.98.0"

default_platform :ios

platform :ios do
  before_all do
    # cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    lint

    scan(
      workspace: "Example/Peloton-UIColors.xcworkspace",
      scheme: "Peloton-UIColors-Example",
      devices: ["iPhone 6s"]
    )
  end

  lane :lint do
    swiftlint(
      mode: :lint,
      ignore_exit_status: false,
      config_file: '.swiftlint.yml'
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end